spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mei?\
    characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: root
    password: 123456
server:
  servlet:
    session:
      timeout: 20s
  jpa:
    show-sql: true
  thymeleaf:
    cache: false
    suffix: .html